version: '3.9'

services:
  app:
    build:
      context: ./node
    image: andr94/node-app
    entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s docker-entrypoint.sh node index.js
    container_name: app
    networks:
      - mynet
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=fcdb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
